// <auto-generated />
namespace Code_First_Jashim.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _502 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_502));
        
        string IMigrationMetadata.Id
        {
            get { return "202111040337314_502"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
